# Alacritty can automatically reload the configuration file when the file is changed by setting the live_config_reload.
live_config_reload = true

# The TERM variable is put under the env key which sets environment variables that are passed to the shell when Alacritty is launched.
[env]
TERM = "xterm-256color"

# By default, Alacritty looks the same as any other terminal emulators for macOS. But there are a handful of options that give it a semi-transparent minimalist look that I find aesthetically pleasing and unique.
[window]
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 8
y = 8

# Font setup
[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Regular Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"


